env:
    browser: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/strict
    - prettier
ignorePatterns:
    - jest.config.ts
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: "packages/*/tsconfig.json"
plugins:
    - "@typescript-eslint"
root: true
